### PR TITLE
Adding the TSpectrum one-dimensional background estimation with SNIP algorithm

### PR DESCRIPTION
**Pull request by cl-fontana**
I added a function that can be applied to datasets that uses the [TSpectrum](https://root.cern.ch/doc/v608/classTSpectrum.html) one-dimensional background estimation.
I used the source of the `shirley_bg()` as a reference, so the new function can be called as:

`@+ = snip_bg(@0, 20, 1, 2, 0)`

It requires several parameters as described more in detail in the [TSpectrum documentation](https://root.cern.ch/root/htmldoc/guides/spectrum/Spectrum.html#background-elimination).
I selected only a subset of the parameters, ignoring the smoothing options, as I think that the smoothing should be done on the data before applying the background estimation, as a separate step.

The function is applied only on the active portions of the dataset, the inactive data are left as they are.
This assumes that the inactive portions are considered background, and thus subtracting them gives zero, in the cleaned up spectrum.

An example of an estimated background follows.

background_estimation

I also added a short description of the function in the data documentation.

So far it I have not added it to the GUI, as the function requires some parameters to work, and I am not sure how it would be sensible to add this to the GUI.
Maybe a GUI call to the function could estimate some default parameters?

### CODE REVIEW

**Comment by wojdyr** [comment]
Thanks! I'll merge it soon. Should it also be accessible from the menu in GUI?
I can add it quickly to the menu, but please suggest how it should look like (in particular what values of the four parameters make sense - can be more than one combination).

I'm inclined to revert back the change from `double` to `Point` in `root/background.cpp`. This is a minor thing - I'll do it later.

**Comment by cl-fontana** [comment]
You're welcome! It feels nice to give back, when you use for free a nice tool as yours.

I am not sure about the GUI. Having played with the algorithm a bit, it looks like that most of the parameters have little effects (besides the `filter_order`).
We could define a set of default parameters. The user then can change them from the terminal interface.

Looking at the parameters in detail:
`snip_bg(@n, window_width, direction, filter_order, estimate_compton)`

1. The `window_width` cannot be bigger than half of the smallest active slice.
The GUI option could guess an example value, by taking, say, a third of the length of the smallest slice.
2. Normally spectra, that we analyze, have a decreasing background, so I think it would be safe to put a -1 for the `direction`.
3. The `filter_order` is probably the most significant parameter with a value of 2 you see the biggest effect. I would say that we can leave this value, so the filter should clear all the peaks by default.
4. The `estimate_compton` usually has very very little effect in the spectra that I have analyzed. I think that it is dedicated to spectra generated by HPGe detectors, that we seldom use. Here I would put a zero (_i.e._ disable this feature).

**Comment by wojdyr** [comment]
Thanks for this addition and apologies for the 3-year delay.
Fityk has been rather neglected in recent years. Now I'll try to make a new release with all the changes accumulated since the previous release. So I merged this PR and simplified it a bit (hopefully without breaking anything).

When comparing the code in fityk/root/background.cpp with the original code in ROOT I see that in your code the first half of `working_space` is returned, and in ROOT it's the second half that is used:
https://github.com/root-project/root/blob/de7bcdff077be4ec08892c1d8349d9f8e62dd420/hist/spectrum/src/TSpectrum.cxx#L1153
I didn't analyze the whole function (it's really long) but I wonder - is it intentional?

I fully understand that after 3 years you may not remember and you may be working in a completely different field now.

**Comment by cl-fontana** [comment]
Luckily I am still working in the same field and I am still happily using fityk! I have just been using the background elimination on a separate step before feeding the spectra to fityk.

I frankly do not remember that particular aspect. I tried to compare the two functions and they seem to match (besides the differences due to the use of `fityk::Point`), the only difference seems to be the return part:
```diff
656,658c640,643
<     working_space.resize(ssize);
<  
<     return working_space;
---
>     for (j = 0; j < ssize; j++)
>         spectrum[j] = working_space[ssize + j];
>     delete[] working_space;
>     return 0;
```
It could be a mistake that I did. What about substituting that return with:
```c++
    std::vector<fityk::Point>::const_iterator begin = working_space.begin() + ssize;
    std::vector<fityk::Point>::const_iterator end = working_space.end();
    return std::vector<fityk::Point>(begin, end);
```

**Comment by wojdyr** [comment]
@cl-fontana I changed it to return the second part of working_space.
And I also changed ROOT::background() back to using `vector<double>`, so it's more similar to the original code.

It's great to know that you're still using fityk!

**Pull request merged**
